---
# Ansible Collections to include in Execution Environment
# These will be bundled into the container image
#
# ⚠️ CRITICAL: Always use EXACT versions (e.g., "1.5.4"), never ranges (e.g., ">=1.5.0")
# Ensures reproducible builds and prevents breaking changes
# See: docs/EE-VERSIONING-STRATEGY.md

collections:
  - name: ansible.posix
    version: 2.1.0  # ✅ Exact version
  - name: ansible.utils
    version: 6.0.0 # ✅ Exact version
  - name: community.general
    version: 12.0.0  # ✅ Exact version
  - name: kubevirt.core
    version: 2.2.3  # ✅ Exact version
  - name: ansible.platform #todo version lock
  - name: ansible.hub
  - name: ansible.eda
  - name: ansible.controller
  - name: infra.aap_configuration