---
# Ansible Collections to include in Execution Environment
# These will be bundled into the container image
#
# ⚠️ CRITICAL: Always use EXACT versions (e.g., "1.5.4"), never ranges (e.g., ">=1.5.0")
# Ensures reproducible builds and prevents breaking changes
# See: docs/EE-VERSIONING-STRATEGY.md

collections:
  # Custom collection from this project
  # ⚠️ For production, pin to specific Git tag (e.g., "qa-v1.1.0"), not "main"
  - name: myorg.custom_collection
    type: git
    source: https://github.com/djdanielsson/rh1-custom-collection.git
    version: main  # ← Change to specific tag for QA/Prod
  
  # AAP Configuration collection (for CaC pipelines)
  # ✅ GOOD: Exact version pinned
  - name: infra.aap_configuration
    version: "2.9.0"
  
  # Core collections
  - name: ansible.posix
    version: "1.5.4"  # ✅ Exact version
  
  - name: ansible.utils
    version: "4.1.0"  # ✅ Exact version
  
  # Community collections
  - name: community.general
    version: "9.5.0"  # ✅ Exact version
  
  # OpenShift Virtualization (for dynamic inventory)
  - name: kubevirt.core
    version: "1.3.0"  # ✅ Exact version
  
  # Add additional collections as needed
  # Example: Cloud providers
  # - name: amazon.aws
  #   version: "9.0.0"  # ✅ Exact version, not >=7.0.0
  # 
  # - name: kubernetes.core
  #   version: "5.0.0"  # ✅ Exact version
  # 
  # Example: Networking
  # - name: cisco.ios
  #   version: "8.0.0"  # ✅ Exact version

# ❌ BAD EXAMPLES (DO NOT USE):
#
# - name: ansible.posix
#   version: ">=1.5.0"  # ❌ Range - will break when 2.0.0 releases
#
# - name: community.general  # ❌ No version - will use latest (non-reproducible)
#
# - name: myorg.custom
#   version: main  # ❌ Mutable ref in production

