apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ansible-builder-run
  annotations:
    pipelinesascode.tekton.dev/task-1: "[git-clone]"
    pipelinesascode.tekton.dev/task-2: ".tekton/tasks/ansible-builder-task.yml"
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
spec:
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
    - name: ansible_galaxy_environment_variables
      value:
        - "ANSIBLE_GALAXY_SERVER_LIST={{ ansible_galaxy_server_list }}"
        - "ANSIBLE_GALAXY_SERVER_PUBLISHED_URL={{ ansible_galaxy_server_published_url }}"
        - "ANSIBLE_GALAXY_SERVER_PUBLISHED_AUTH_URL={{ ansible_galaxy_server_published_auth_url }}"
        - "ANSIBLE_GALAXY_SERVER_PUBLISHED_TOKEN={{ ansible_galaxy_server_published_token }}"
        - "ANSIBLE_GALAXY_SERVER_VALIDATED_URL={{ ansible_galaxy_server_validated_url }}"
        - "ANSIBLE_GALAXY_SERVER_VALIDATED_AUTH_URL={{ ansible_galaxy_server_validated_auth_url }}"
        - "ANSIBLE_GALAXY_SERVER_VALIDATED_TOKEN={{ ansible_galaxy_server_validated_token }}"
        - "ANSIBLE_GALAXY_SERVER_COMMUNITY_URL={{ ansible_galaxy_server_community_url }}"
  pipelineSpec:
    workspaces:
    - name: shared-workspace
    tasks:
      - name: fetch-source
        taskRef:
          name: git-clone
        params:
        - name: url
          value: "{{ repo_url }}"
        - name: revision
          value: "{{ revision }}"
        - name: verbose
          value: "true"
        workspaces:
        - name: output
          workspace: shared-workspace

      - name: ansible-builder
        runAfter:
        - fetch-source
        taskRef:
          name: ansible-builder
        workspaces:
        - name: source
          workspace: shared-workspace

      - name: build-image
        taskRef:
          resolver: cluster
          params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
        params:
        - name: IMAGE
          value: "myregistry.io/rh1-ee:asdf"
        - name: DOCKERFILE
          value: "Containerfile"
        - name: CONTEXT
          value: "context"
        - name: SKIP_PUSH
          value: "true"
        - name: VERBOSE
          value: "true"
        - name: BUILD_ARGS
          value: $(params.ansible_galaxy_environment_variables)
        workspaces:
        - name: source
          workspace: shared-workspace
        runAfter:
        - ansible-builder